### PR TITLE
fix: add mskAuth to kafka depedencies

### PR DESCRIPTION
**Pull request by piotrek660**
kafka-enrich is throwing Class software.amazon.msk.auth.iam.IAMClientCallbackHandler could not be found.

### CODE REVIEW

**Comment by istreeter** [comment]
Thank you @piotrek660!  This looks like a good improvement.  We can get this into the next release.

**Comment by oguzhanunlu** [comment]
GitHub doesn't allow fork repositories to read secrets hence the CI failure here

**Comment by oguzhanunlu** [comment]
To double-check, I cherry-picked this commit and opened a new PR at https://github.com/snowplow/enrich/pull/752 , the tests are successful. Merging this PR, thank you very much for the contribution @piotrek660 !

**Comment by piotrek660** [comment]
cool, thx!

**Pull request merged**
