### PR TITLE
Common: add toThrift and toRaw methods to CollectorPayload (close #345)

### LINKED ISSUE #345: Common: add toThrift and toRaw methods to CollectorPayload
Reverse of `ThriftLoader.toCollectorPayload`.

For testing and debugging purposes.

### PR DESCRIPTION
**Pull request by benjben**

### CODE REVIEW

**Review by chuwy — APPROVED** [review]
Looks awesome!

**Comment by chuwy** [comment]
Hey @benjben! Do you mind me adding #358 and #357 to this PR? They're also auxuliary commits without any impact on the assets.

**Comment by benjben** [comment]
Sure @chuwy !

**Comment by chuwy** [comment]
Added those and couple of minor bumps to make Snyk completely happy. @oguzhanunlu could you have a look?

**Comment by oguzhanunlu** [comment]
It seems CI isn't happy @chuwy , is that expected?

**Comment by chuwy** [comment]
No, not expected - you're right. I added this check in #357 because it it will break publishing. Will fix it now.

**Comment by chuwy** [comment]
Green now, @oguzhanunlu (no idea what those -0.02%).

**Review by oguzhanunlu — APPROVED** [review]
LGTM!

**Pull request merged**
